### ISSUE TITLE
Smoke Intensity + Direction

### ISSUE THREAD

**Issue by Kingstell1** [KapitanFloww/FlowwSmoke#16]
Hey, I saw in the code that you had put smoke intensity as To-Do. Is that still something you were working on? I was also interested in adding something that could let the user define the direction in which the smoke goes as it rises. Is this anything that you've looked into or is it not in the scope of the project?

**Comment by KapitanFloww** [comment]
Hi there and thank you for the message.
I've neglected the project a bit in the past for personal reasons. 🫠
We are currently on holiday 🎄, afterwards I will be happy to tackle the topics. 
It's both definitely within scope! 😎
Also, feel free to contribute by yourself! 💪🏻

**Comment by KapitanFloww** [comment]
Just for clarification, do you want to set the intensity individually per smoke-location or globally for all smokes?
